AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

  AllCops:
    Exclude:
      - 'old_angel_bling.gemspec'


Layout/LineLength:
  Max: 120
